#!/bin/bash

# Copyright (C) 2021 Toitware ApS. All rights reserved.
# Use of this source code is governed by an MIT-style license that can be
# found in the LICENSE file.

EXTENSIONS="*.go *.proto"

new_files=$(git diff --name-only --diff-filter=A --cached -- $EXTENSIONS)

for f in $new_files; do
  if ! grep -l "Copyright .* Toitware" "$f" 2>&1 1>/dev/null; then
    missing_copyright="$f $missing_copyright"
  else
    if ! grep -l "governed.*\(MIT\|BSD\)" "$f"  2>&1 1>/dev/null; then
      missing_governed="$f $missing_governed"
    fi
  fi
done

if [[ -n "$missing_copyright" ]]; then
  echo "Missing copyright in:"
  for f in $missing_copyright; do
    echo "  $f"
  done
fi

if [[ -n "$missing_governed" ]]; then
  echo "Missing governed line:"
  for f in $missing_governed; do
    echo "  $f"
  done
fi

if [ -n "$missing_copyright" ] || [ -n "$missing_governed" ]; then
  exit 1;
fi
